FROM php:8.1-fpm

WORKDIR /app

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt-get update && apt-get install -y \
    zip \
    unzip \
    git \
    curl

RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN docker-php-ext-install bcmath
RUN docker-php-ext-install sockets

COPY . .

RUN chmod -R 777 storage bootstrap/cache

USER root

EXPOSE 9000
